version: '3'

networks:
  example-network:
    name: example-network
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.16.238.0/24

services:
  coordinator:
    image: coordinator
    ports:
      - "6060:6060"
    networks:
      - example-network

  gateway:
    image: gateway
    ports:
      - "5050:5050"
    environment:
      cma_host: http://localhost:3010
      cr_host: http://localhost:4000
    depends_on:
      - cma
      - cr
    networks:
      - example-network

  cma:
    image: cmamicroservice
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "3010-3012:3010"
    networks:
      - example-network

  cr:
    image: contentrecomendationmicroservice
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "4000-4002:4000"
    networks:
      - example-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/cma.conf:ro
      - ./nginx:/etc/nginx/cr.conf:ro
    depends_on:
      - cma
      - cr

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - example-network
      # my_network:
      #  ipv4_address: 172.16.238.11
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    networks:
      - example-network
    depends_on:
      - prometheus

