version: '3'

networks:
  my_network:
    driver: bridge

services:
  coordinator:
    image: coordinator
    ports:
      - "6060:6060"
    networks:
      - my_network

  gateway:
    image: gateway
    ports:
      - "5050:5050"
    environment:
      cma_host: http://localhost:3000
      cr_host: http://localhost:4000
    depends_on:
      - cma
      - cr
    networks:
      - my_network

  cma:
    image: cmamicroservice
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "3000-3002:3000"
    networks:
      - my_network

  cr:
    image: contentrecomendationmicroservice
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "4000-4002:4000"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/cma.conf:ro
      - ./nginx.conf:/etc/nginx/cr.conf:ro
    depends_on:
      - cma
      - cr

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - my_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

