global:
  scrape_interval: 60s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 1m
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'gateway'
  static_configs:
    - targets: ['localhost:5050']

remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: 1284187
      password: glc_eyJvIjoiOTg5MDQ0IiwibiI6InN0YWNrLTc4ODE0My1pbnRlZ3JhdGlvbi1tZXRyaWNzIiwiayI6IlBJS09rOTY3ZXAyWDFlMDYxUFZKVDBINCIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19
